using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Server;
using Entities;
using System.Collections.Generic;
using Constants;

namespace ServerLogicTests
{
    [TestClass]
    public class AnswerAQuestion
    {
        private IServer _server;
        private Question _q;

        [TestInitialize]
        public void TestInitialize()
        {
            _server = new ServerImpl(new FakeMedTrainDBContext());
            _server.login("defaultadmin@gmail.com", "password");
            _server.addSubject(100000, "subject");
            _server.addTopic(100000, "subject", "topic");
            _server.addQuestion(100000, "subject", true, "", new List<string>() { "topic" });
        }

        // string AnswerAQuestion(int userUniqueInt, int questionID, bool isNormal, int normalityCertainty, List<string> diagnoses, List<int> diagnosisCertainties);

        private void setup()
        {
            _server.getAutoGeneratedQuesstion(100000, "subject", "topic");
            _q = _server.getNextQuestion(100000).Item2;
        }

        [TestMethod]
        public void answerAQuestionUserNotLoggedIn()
        {
            setup();
            _server.logout(100000);
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, true, 5, new List<string>(), new List<int>());
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }


        [TestMethod]
        public void answerAQuestionWrongUserId()
        {
            setup();
            string s = _server.AnswerAQuestion(99999, _q.QuestionId, true, 5, new List<string>(), new List<int>());
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionWrongQuestionId()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, 0, true, 5, new List<string>(), new List<int>());
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionNormalityCertaintyIsZero()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, true, 0, new List<string>(), new List<int>());
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionNormalityCertaintyIsNegative()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, true, -1, new List<string>(), new List<int>());
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionNormalityCertaintyIsOverTen()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, true, 11, new List<string>(), new List<int>());
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionDiagnosesIsNull()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, true, 5, null, new List<int>());
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionDiagnosesContainsNull()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, true, 5, new List<string>() { null }, new List<int>() { 5 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionDiagnosesContainsNullString()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "null" }, new List<int>() { 5 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionDiagnosesContainsEmptyString()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "" }, new List<int>() { 5 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionDiagnosesContainsNonExistingTopic()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "no_topic" }, new List<int>() { 5 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestionCertaintiesIsNull()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, true, 5, new List<string>(), null);
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioCertaintiesContainsZero()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "topic" }, new List<int>() { 0 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioCertaintiesContainsNegativeNumber()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "topic" }, new List<int>() { -1 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioCertaintiesContainsNumberOverTen()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "topic" }, new List<int>() { 11 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioMoreDiagnosesThanCertainties()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "topic" }, new List<int>());
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioMoreCertaintiesThanDiagnoses()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>(), new List<int>() { 5 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioNoQuestionRequested()
        {
            string s = _server.AnswerAQuestion(100000, 1, false, 5, new List<string>() { "topic" }, new List<int>() { 5 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioNormalWithDiagnoses()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, true, 5, new List<string>() { "topic" }, new List<int>() { 5 });
            Assert.IsFalse(s.Equals(Replies.NEXT));
            Assert.IsFalse(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioSingleQuestion()
        {
            setup();
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "topic" }, new List<int>() { 5 });
            Assert.IsTrue(s.Equals(Replies.SHOW_ANSWER));
        }

        [TestMethod]
        public void answerAQuestioFromTestAnswerAfterEveryQuestion()
        {
            _server.addQuestion(100000, "subject", true, "", new List<string>() { "topic" });
            _server.getAutoGeneratedTest(100000, "subject", "topic", 2, true);
            _q = _server.getNextQuestion(100000).Item2;
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "topic" }, new List<int>() { 5 });
            Assert.IsTrue(s.Equals(Replies.SHOW_ANSWER));
        }
        
        [TestMethod]
        public void answerAQuestioFromTestAnswersAtTheEnd()
        {
            _server.addQuestion(100000, "subject", true, "", new List<string>() { "topic" });
            _server.getAutoGeneratedTest(100000, "subject", "topic", 2, false);
            _q = _server.getNextQuestion(100000).Item2;
            string s = _server.AnswerAQuestion(100000, _q.QuestionId, false, 5, new List<string>() { "topic" }, new List<int>() { 5 });
            Assert.IsTrue(s.Equals(Replies.NEXT));
        }
    }
}
