using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.Collections.Generic;
using Constants;
using Server;
using Entities;
using DB;

namespace ServerLogicTests
{
    [TestClass]
    public class GetAutoGeneratedTest
    {
        private IServer _server;

        [TestInitialize]
        public void TestInitialize()
        {
            _server = new ServerImpl(new DB.FakeMedTrainDBContext());
            _server.login("defaultadmin@gmail.com", "password");
            _server.addSubject(Users.USER_UNIQUE_INT, "subject");
            _server.addTopic(Users.USER_UNIQUE_INT, "subject", "topic");
        }

        [TestMethod]
        public void getAutoGeneratedTestUserNotLoggedIn()
        {
            int userId = _server.register("user@gmail.com", "password", Users.medicalTrainingLevels[0], "fn", "ln").Item2;
            Assert.IsFalse(_server.getAutoGeneratedTest(userId, "subject", new List<string>() { "topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestNonExistingSubject()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "no_subject", new List<string>() { "topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestNonExistingTopic()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "no_topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestNoQuestions()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestWrongUserId()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(99999, "subject", new List<string>() { "topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestSubjectIsNull()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, null, new List<string>() { "topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestSubjectIsNullString()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "null", new List<string>() { "topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestSubjectIsEmpty()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "", new List<string>() { "topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestTopicIsNull()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", null, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestTopicIsNullString()
        {
            _server.login("defaultadmin@gmail.com", "password");
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "null" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestTopicIsEmpty()
        {
            _server.login("defaultadmin@gmail.com", "password");
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestOneQuestionAnswerEveryTime()
        {
            _server.createQuestion(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, new List<byte[]>(), "");
            Assert.IsTrue(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, 1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestOneQuestionAnswerAtEnd()
        {
            _server.createQuestion(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, new List<byte[]>(), "");
            Assert.IsTrue(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, 1, false).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestNotEnoughQuestions()
        {
            _server.createQuestion(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, new List<byte[]>(), "");
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, 2, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestZeroQuestions()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, 0, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestNegativeNumberOfQuestions()
        {
            Assert.IsFalse(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, -1, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestTwoQuestionsAnswerEveryTime()
        {
            _server.createQuestion(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, new List<byte[]>(), "");
            _server.createQuestion(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, new List<byte[]>(), "");
            Assert.IsTrue(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, 2, true).Equals(Replies.SUCCESS));
        }

        [TestMethod]
        public void getAutoGeneratedTestTwoQuestionsAnswerAtEnd()
        {
            _server.createQuestion(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, new List<byte[]>(), "");
            _server.createQuestion(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, new List<byte[]>(), "");
            Assert.IsTrue(_server.getAutoGeneratedTest(Users.USER_UNIQUE_INT, "subject", new List<string>() { "topic" }, 2, false).Equals(Replies.SUCCESS));
        }
    }
}
