using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace ServerLogicTests
{
    [TestClass]
    public class GetAutoGeneratedTest
    {
        [TestMethod]
        public void TestMethod1()
        {
        }

        // there is a question but user request more
        // less than 1 question (0 and negative)
        // every test with both true and false
    }
}
