using communication.Core;
using communication.Models.GetTest;
using Constants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace communication.Controllers
{
    public class GetTestController : Controller
    {
        [HttpGet]
        // GET: GetTest
        public ActionResult Index()
        {
            List<GetTestData> data = new List<GetTestData>();
            List<string> subjects = ServerWiring.getInstance().getAllSubjects();
            foreach (string subject in subjects)
            {
                List<string> list = ServerWiring.getInstance().getSubjectTopics(subject);
                data.Add(new GetTestData(subject, list));
            }
            return View();
        }

        [HttpGet]
        public List<string> SubjectChanged(string subject)
        {
            return ServerWiring.getInstance().getSubjectTopics(subject);

        }

        [HttpPost]
        public ActionResult Submit(string subject, string topic, int numberOfQuestions, string whenToShowAnswer)
        {

            ViewBag.subject = subject;
            ViewBag.topic = topic;
            ViewBag.numberOfQuestions = numberOfQuestions;
            bool flag = false;
            if (whenToShowAnswer.Equals("AfterEachQuestion"))
            {
                flag = true;
            }
            string ans = ServerWiring.getInstance().getAutoGeneratedTest(Convert.ToInt32("100000"), subject, topic, numberOfQuestions, flag);
            if (ans == Replies.SUCCESS)
            {
                return RedirectToAction("Index", "AnswerQuestion");
            }
            ViewBag.errorMessage = ans;
            return View("index");
        }
    }
}