using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;

namespace Server
{
    public interface IServer
    {
        #region users manager
        Tuple<string, int> register(string email, string password, string medicalTraining, string firstName, string lastName);

        Tuple<string, int> login(string email, string password);

        string restorePassword(string email);

        string setUserAsAdmin(int userUniqueInt, string usernameToTurnToAdmin);
        #endregion
        #region system extensions
        string addSubject(int userUniqueInt, string subject);

        string addTopic(int userUniqueInt, string subject, string topic);
        #endregion
        // need to create a seperate class
        #region self training manager
        string getAutoGeneratedQuesstion(int userUniqueInt, string subject, List<string> topics);

        string getAutoGeneratedTest(int userUniqueInt, string subject, List<string> topics, int numOfQuestions, bool answerEveryTime);

        bool hasMoreQuestions(int userUniqueInt);

        Tuple<string, Question> getNextQuestion(int userUniqueInt);

        Tuple<string, int> answerAQuestion(int userUniqueInt, int questionID, bool isNormal, int normalityCertainty, List<string> diagnoses, List<int> diagnosisCertainties, bool isAutoGenerated);

        Tuple<string, List<Question>> getAnsweres(int userUniqueInt);
        #endregion
        #region questions manager
        // allows empty list of images for tests
        string createQuestion(int userUniqueInt, string subject, List<string> qDiagnoses, List<byte[]> allImgs, string freeText);

        string saveSelectedSubjectTopic(int userUniqueInt, string subject, List<string> topicsList);

        Tuple<string, List<Question>> getAllReleventQuestions(int userUniqueInt);

        string removeQuestions(int userUniqueInt, List<Tuple<int, string>> questionsIdsList);

        List<string> getQuestionImages(int questionId);

        List<string> getQuestionDiagnoses(int questionId);
        #endregion
        Tuple<string, Question> getNextQuestionGroupTest(int userUniqueInt, string group, int test);

        // has tests - 100% coverage
        List<string> getAllSubjects();

        // has tests - 100% coverage
        // change name - excluding normal
        List<string> getSubjectTopicsGetAQuestion(string subject);

        // change name - including normal
        List<string> getSubjectTopicsCreateAQuestion(string subject);

        // 100% coverage
        void logout(int userUniqueInt);

        // has tests - 100% coverage
        User isLoggedIn(int userUniqueInt);

        // has tests - 100% coverage
        string getUserName(int userUniqueInt);

        // has tests - 100% coverage
        string createGroup(int userUniqueInt, string groupName, string inviteEmails, string emailContent);

        // has tests - 100% coverage
        string inviteToGroup(int userUniqueInt, string groupName, string inviteEmails, string emailContent);

        // has tests - 100% coverage
        Tuple<string, List<string>> getAllAdminsGroups(int userUniqueInt);

        // has tests - 100% coverage
        string removeGroup(int userUniqueInt, string groupName);

        string createTest(int userUniqueInt, string subject, List<string> topics);

        List<Question> getTestQuestions(int userUniqueInt);

        string createTest(int userUniqueInt, List<int> questionsIds, string name);

        bool isAdmin(int userUniqueInt);

        Tuple<string, List<Test>> getAllTests(int userUniqueInt, string subject);

        string addTestToGroup(int userUniqueInt, string groupName, int testId);
        
		Tuple<string, List<String>> getUsersGroups(int userUniqueInt);

        Tuple<string, List<String>> getUsersGroupsInvitations(int userUniqueInt);
        
        string answerAQuestionGroupTest(int userUniqueInt, string group, int test, int questionID, bool isNormal, int normalityCertainty, List<string> diagnoses, List<int> diagnosisCertainties);
        
        string acceptUsersGroupsInvitations(int userUniqueInt, List<String> groups);
        
        bool hasMoreQuestionsGroupTest(int userUniqueInt, string group, int test);

        Tuple<string, List<Tuple<string, int>>> getUnfinishedTests(int userUniqueInt, string groupName);
        
        Tuple<string, List<Tuple<string, int>>> getFinishedTests(int userUniqueInt, string groupName);

        string saveGroupAndTest(int userUniqueInt, string groupName, int testId);

        Tuple<string, Tuple<string, int>> getSavedGroupAndTest(int userUniqueInt);

        Tuple<string, List<Question>> getTestQuestionsByTestId(int userUniqueInt, int testId);

        Tuple<string, List<Tuple<string, int, int,int, int>>> getPastGroupGrades(int userUniqueInt, string groupName);

        string declineUsersGroupsInvitations(int userUniqueInt, List<String> groups);

        double getTestGrade(int userUniqueInt, string group, int testId);

        Tuple<string, List<Test>> getGroupTests(int adminId, string group);

        Tuple<string, List<Tuple<string, int>>> getGrades(int adminId, int testId, string groupName);
    }
}
